export declare const signPrefix: string;
export declare const deleteTopSymbol = "-";
export declare const deleteBottomSymbol = "_";
export declare const deleteTopAndBottomSymbol = "[";
export declare const addSymbol = "+";
export declare const modifySymbol = "~";
export declare const signGroups: {
    [deleteTopSymbol]: string;
    [deleteBottomSymbol]: string;
    [deleteTopAndBottomSymbol]: string;
    [addSymbol]: string;
    [modifySymbol]: string;
};
export declare const delayGap = 200;
export declare const ignorePrefix: string[];
export declare const second = 1000;
export declare const minute: number;
export declare const hour: number;
export declare const day: number;
export declare const year: number;
export declare const month: number;
export declare const blameKeys: string[];
export declare const emptyHash = "0000000000000000000000000000000000000000";
